OPTIONS  https://us-central1-residentappv2-affc6.cloudfunctions.net/corsEnabledFunction
###
DELETE https://us-central1-residentappv2-affc6.cloudfunctions.net/api

###
POST https://us-central1-residentappv2-affc6.cloudfunctions.net/deleteUserByEmail
content-type: application/json

{
  "uid": "fgNlQVlgEwMMM2ddVEAlJUgakzm2"
}
