GET  https://us-central1-residentappv2-affc6.cloudfunctions.net/us-central1-residentappv2-affc6.cloudfunctions.net/api/getAllusers
###
GET https://us-central1-residentappv2-affc6.cloudfunctions.net/api/requestUsers/

###
POST https://us-central1-residentappv2-affc6.cloudfunctions.net/deleteUserByEmail
content-type: application/json

{
  "uid": "fgNlQVlgEwMMM2ddVEAlJUgakzm2"
}
